// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdVdwO7qgG_9HH1oXOUicYRhUHKZvtV8c',
    appId: '1:750939161265:web:13c6ecc726b5602339d890',
    messagingSenderId: '750939161265',
    projectId: 'todoflutter-eb86e',
    authDomain: 'todoflutter-eb86e.firebaseapp.com',
    storageBucket: 'todoflutter-eb86e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkjL_0-MzTzkYdcshKG4VGikzePQmWILQ',
    appId: '1:750939161265:android:8e179f74e0b6bba939d890',
    messagingSenderId: '750939161265',
    projectId: 'todoflutter-eb86e',
    storageBucket: 'todoflutter-eb86e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkVWnOQ-rX0oIlZaRkJeisbuxwVAlzpe8',
    appId: '1:750939161265:ios:4cffca4034e2a0f239d890',
    messagingSenderId: '750939161265',
    projectId: 'todoflutter-eb86e',
    storageBucket: 'todoflutter-eb86e.firebasestorage.app',
    iosBundleId: 'com.example.todoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkVWnOQ-rX0oIlZaRkJeisbuxwVAlzpe8',
    appId: '1:750939161265:ios:4cffca4034e2a0f239d890',
    messagingSenderId: '750939161265',
    projectId: 'todoflutter-eb86e',
    storageBucket: 'todoflutter-eb86e.firebasestorage.app',
    iosBundleId: 'com.example.todoFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdVdwO7qgG_9HH1oXOUicYRhUHKZvtV8c',
    appId: '1:750939161265:web:823edbcc30e399d239d890',
    messagingSenderId: '750939161265',
    projectId: 'todoflutter-eb86e',
    authDomain: 'todoflutter-eb86e.firebaseapp.com',
    storageBucket: 'todoflutter-eb86e.firebasestorage.app',
  );
}
